### ISSUE TITLE
Make blocks properly Wither proof

### ISSUE THREAD

**Issue by vadis365** [vadis365/Mob-Grinding-Utils#90]
Looks like the Mob Masher still is broken by the wither, so I'll make them along with the Fans, Absorption Hopper, Tanks etc all unbreakable by it.

**Comment by vadis365** [comment]
done

**Comment by bbf** [comment]
Hey vadis365, I think you forgot to add the Wither protection (override for canEntityDestroy()) to the masher itself (BlockSaw).

**Comment by Drakma** [comment]
This appears to be back in 0.3.13 
(using Forge 14.23.5.2838)
